#!/bin/bash

# To use important variables from command line use the following code:
PTEMPDIR=$1 # First argument is temp folder during install
PSHNAME=$2  # Second argument is Plugin-Name for scipts etc.
PDIR=$3     # Third argument is Plugin installation folder
PVERSION=$4 # Forth argument is Plugin version

echo "<INFO> Stopping and removing unifi service"
# ExecStop of the unit runs "docker compose down" (removes container + network).
systemctl stop unifi
systemctl disable unifi
rm -f /etc/systemd/system/unifi.service
systemctl daemon-reload

echo "<INFO> Removing unifi-controller container (fallback, in case compose down did not run)"
docker rm -f unifi-controller 2>/dev/null

echo "<INFO> Removing unifi-controller docker image(s) to free disk space"
IMAGES=$(docker images 'linuxserver/unifi-controller' -q | sort -u)
if [ -n "$IMAGES" ]; then
    docker rmi -f $IMAGES 2>/dev/null
fi

# NOTE: The Docker engine and Portainer are intentionally NOT removed here. They
# are provided by the Docker plugin and shared with other plugins/containers.
# The plugin files and the UniFi data (data/plugins/unifi) are removed by LoxBerry.

exit 0
