---
version: "2.1"
services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    container_name: unifi-controller
    env_file:
      - REPLACELBPCONFIGDIR/unifi.env
    environment:
      - MEM_LIMIT=1024M #optional
    volumes:
      - REPLACELBPDATADIR/data:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
     
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped