home:
  route: '/'
  controller: 'LoxBerryPoppinsPlugin\Controller\HomeController'
  action: 'indexPage'

logs:
  route: '/logs'
  controller: 'LoxBerryPoppinsPlugin\Controller\HomeController'
  action: 'logsPage'

#  Full configuration could look like this:
#  someRoute:
#    route: '/'
#    controller: 'LoxBerryPoppinsPlugin\Controller\SomeController'
#    method: 'GET,POST' <- GET is assumed if not provided
#    public: true <- false is assumed if not provided
